-- MySQL Script generated by MySQL Workbench
-- Sat Oct 19 06:58:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blogging_app_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogging_app_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogging_app_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `blogging_app_db` ;

-- -----------------------------------------------------
-- Table `blogging_app_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogging_app_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogging_app_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  `token` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app_db`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogging_app_db`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app_db`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogging_app_db`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_userid` (`user_id` ASC) VISIBLE,
  INDEX `fk_postid` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_postid`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app_db`.`posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app_db`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogging_app_db`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `comment_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `post_id` (`post_id` ASC) VISIBLE,
  INDEX `comment_id` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `likes_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app_db`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `likes_ibfk_2`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app_db`.`posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `likes_ibfk_3`
    FOREIGN KEY (`comment_id`)
    REFERENCES `blogging_app_db`.`comments` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app_db`.`post_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogging_app_db`.`post_categories` (
  `post_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `category_id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `post_categories_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app_db`.`posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `post_categories_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `blogging_app_db`.`categories` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blogging_app_db`.`post_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogging_app_db`.`post_users` (
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `post_users_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogging_app_db`.`posts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `post_users_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogging_app_db`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
